//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EulerProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4445,2697,5115,718,2209,2212,654,4348,3079,6821,7668,3276,8874,4190,3785,2752,9473,7817,9137,496,7338,3434,7152,4355,4552,7917,7827,2460,2350,691,3514,5880,3145,7633,7199,3783,5066,7487,3285,1084,8985,760,872,8609,8051,1134,9536,5750,9716,9371,7619,5617,275,9721,2997,2698,1887,8825,6372,3014,2113,7122,7050,6775,5948,2758,1219,3539,348,7989,2735,9862,1263,8089,6401,9462,3168,2758,3748,5870
        ///1096,20,1318,7586,5167,2642,1443,5741,7621,7030,5526,4244,2348,4641,9827,2448,6918,5883,3737,300,7116,6531,567,5997,3971 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p081_matrix {
            get {
                return ResourceManager.GetString("p081_matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid 01
        ///003020600
        ///900305001
        ///001806400
        ///008102900
        ///700000008
        ///006708200
        ///002609500
        ///800203009
        ///005010300
        ///Grid 02
        ///200080300
        ///060070084
        ///030500209
        ///000105408
        ///000000000
        ///402706000
        ///301007040
        ///720040060
        ///004010003
        ///Grid 03
        ///000000907
        ///000420180
        ///000705026
        ///100904000
        ///050000040
        ///000507009
        ///920108000
        ///034059000
        ///507000000
        ///Grid 04
        ///030050040
        ///008010500
        ///460000012
        ///070502080
        ///000603000
        ///040109030
        ///250000098
        ///001020600
        ///080060020
        ///Grid 05
        ///020810740
        ///700003100
        ///090002805
        ///009040087
        ///400208003
        ///160030200
        ///302700060
        ///005600008
        ///076051090
        ///Grid 06
        ///100920000
        ///5240 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p096_sudoku {
            get {
                return ResourceManager.GetString("p096_sudoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid 01
        ///003020600
        ///900305001
        ///001806400
        ///008102900
        ///700000008
        ///006708200
        ///002609500
        ///800203009
        ///005010300
        ///Grid 02
        ///200080300
        ///060070084
        ///030500209
        ///000105408
        ///000000000
        ///402706000
        ///301007040
        ///720040060
        ///004010003
        ///Grid 03
        ///000000907
        ///000420180
        ///000705026
        ///100904000
        ///050000040
        ///000507009
        ///920108000
        ///034059000
        ///507000000
        ///Grid 04
        ///030050040
        ///008010500
        ///460000012
        ///070502080
        ///000603000
        ///040109030
        ///250000098
        ///001020600
        ///080060020
        ///Grid 05
        ///020810740
        ///700003100
        ///090002805
        ///009040087
        ///400208003
        ///160030200
        ///302700060
        ///005600008
        ///076051090
        ///Grid 06
        ///100923000
        ///5240 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p096_sudoku_modif {
            get {
                return ResourceManager.GetString("p096_sudoku_modif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 519432,525806
        ///632382,518061
        ///78864,613712
        ///466580,530130
        ///780495,510032
        ///525895,525320
        ///15991,714883
        ///960290,502358
        ///760018,511029
        ///166800,575487
        ///210884,564478
        ///555151,523163
        ///681146,515199
        ///563395,522587
        ///738250,512126
        ///923525,503780
        ///595148,520429
        ///177108,572629
        ///750923,511482
        ///440902,532446
        ///881418,505504
        ///422489,534197
        ///979858,501616
        ///685893,514935
        ///747477,511661
        ///167214,575367
        ///234140,559696
        ///940238,503122
        ///728969,512609
        ///232083,560102
        ///900971,504694
        ///688801,514772
        ///189664,569402
        ///891022,505104
        ///445689,531996
        ///119570,591871
        ///821453,508 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p099_base_exp {
            get {
                return ResourceManager.GetString("p099_base_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -340,495,-153,-910,835,-947
        ///-175,41,-421,-714,574,-645
        ///-547,712,-352,579,951,-786
        ///419,-864,-83,650,-399,171
        ///-429,-89,-357,-930,296,-29
        ///-734,-702,823,-745,-684,-62
        ///-971,762,925,-776,-663,-157
        ///162,570,628,485,-807,-896
        ///641,91,-65,700,887,759
        ///215,-496,46,-931,422,-30
        ///-119,359,668,-609,-358,-494
        ///440,929,968,214,760,-857
        ///-700,785,838,29,-216,411
        ///-770,-458,-325,-53,-505,633
        ///-752,-805,349,776,-799,687
        ///323,5,561,-36,919,-560
        ///-907,358,264,320,204,274
        ///-728,-466,350,969,292,-345
        ///940,836,272,-533,748,185
        ///411,998,813,52 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p102_triangles {
            get {
                return ResourceManager.GetString("p102_triangles", resourceCulture);
            }
        }
    }
}
